TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += icp7215.db
DB += icp7026.db
DB += icp7267.db
DB += icp7060.db
DB += icp7250.db
DB += icp7226.db
DB += modbusDevice.db

DB += icprtdsensor.template
DB += modbusAI.template
DB += modbusDO.template

# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

